server:
  port: 8200

spring:
  application:
    name: svc-banking
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    packages-to-scan: com.aurix.platform.banking,com.aurix.platform.shared,com.aurix.platform.organization

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
  server:
    port: 9200
  health:
    db:
      enabled: false
    redis:
      enabled: false
    kafka:
      enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
