package com.aurix.platform.customer.onboarding.entity;

public enum StatusOnboarding {
    RECEBIDA, DOCUMENTOS_PENDENTES, EM_ANALISE_KYC, KYC_APROVADO, KYC_REJEITADO, EM_ANALISE_MANUAL, APROVADA, REJEITADA, CONTA_CRIADA,
    EM_PREENCHIMENTO, CNPJ_CONSULTADO, SOCIOS_VALIDADOS, DOCUMENTOS_ANALISADOS, AML_APROVADO, COMPLIANCE_APROVADO, EM_ASSINATURA, CONTRATO_ASSINADO;
}
