-- ============================================================
-- Aurix Core Banking - Módulos de Produtos e Contratos (V2)
-- Gere a partir das entidades JPA (ver docs/migracoes-banco.md)
-- ============================================================
CREATE SCHEMA IF NOT EXISTS aurix;

-- ------------------------------------------------------------
-- Catálogo de produtos (svc-products)
-- ------------------------------------------------------------
create table aurix.produtos (id bigint generated by default as identity, data_atualizacao timestamp(6), data_criacao timestamp(6) not null, tenant_id varchar(64), versao integer not null, ativo boolean not null, codigo varchar(50) not null unique, descricao varchar(500), exigencia_minima varchar(500), nome varchar(200) not null, numero_versao integer not null, publico_alvo varchar(200), requisitos JSONB, status varchar(30) not null check ((status in ('RASCUNHO','ATIVO','INATIVO','DESCONTINUADO'))), tipo_produto varchar(30) not null check ((tipo_produto in ('CONTA_CORRENTE','CONTA_POUPANCA','CREDITO','INVESTIMENTO','SEGURO','CAMBIO','CARTAO','CONSIGNADO','FINANCIAMENTO','OUTROS'))), vigencia_fim date, vigencia_inicio date, primary key (id));
create table aurix.regras_elegibilidade (id bigint generated by default as identity, data_atualizacao timestamp(6), data_criacao timestamp(6) not null, tenant_id varchar(64), versao integer not null, ativa boolean not null, comparador varchar(20) not null check ((comparador in ('MAIOR_IGUAL','MENOR_IGUAL','IGUAL','DIFERENTE'))), descricao varchar(300), produto_id bigint not null, tipo_regra varchar(30) not null check ((tipo_regra in ('RENDA_MINIMA','IDADE_MINIMA','IDADE_MAXIMA','SCORE_MINIMO','SEGMENTO','TIPO_PESSOA','NAO_NEGATIVADO'))), valor_numerico numeric(19,4), valor_texto varchar(50), primary key (id));
create table aurix.tarifas_produto (id bigint generated by default as identity, data_atualizacao timestamp(6), data_criacao timestamp(6) not null, tenant_id varchar(64), versao integer not null, codigo varchar(50) not null unique, descricao varchar(300) not null, obrigatoria boolean not null, percentual numeric(9,4), periodicidade varchar(20) not null check ((periodicidade in ('MENSAL','ANUAL','UNICO','POR_EVENTO'))), produto_id bigint not null, tipo_tarifa varchar(30) not null check ((tipo_tarifa in ('MANUTENCAO','TRANSFERENCIA','SAQUE','EXTRATO','PACOTE','TAXA_JUROS','TARIFA','OUTROS'))), valor_fixo numeric(19,4), vigencia_fim date, vigencia_inicio date, primary key (id));
create table aurix.versoes_produto (id bigint generated by default as identity, data_atualizacao timestamp(6), data_criacao timestamp(6) not null, tenant_id varchar(64), versao integer not null, autor varchar(100), changelog varchar(500), dados_json JSONB, data_versao timestamp(6) not null, numero_versao integer not null, produto_id bigint not null, status varchar(20) not null check ((status in ('RASCUNHO','PUBLICADA','SUBSTITUIDA'))), primary key (id));

-- ------------------------------------------------------------
-- Gestão de contratos (svc-contracts)
-- ------------------------------------------------------------
create table aurix.contratos (id bigint generated by default as identity, data_atualizacao timestamp(6), data_criacao timestamp(6) not null, tenant_id varchar(64), versao integer not null, assinatura_digital JSONB, cliente_documento varchar(14), cliente_id bigint not null, dados_json JSONB, data_assinatura timestamp(6), data_vigencia_fim date, data_vigencia_inicio date, numero_contrato varchar(50) not null unique, prazo_meses integer, produto_codigo varchar(50), produto_id bigint, status varchar(30) not null check ((status in ('RASCUNHO','AGUARDANDO_ASSINATURA','ASSINADO','ATIVO','LIQUIDADO','CANCELADO','REJEITADO'))), taxa_juros numeric(9,4), termos_texto TEXT, tipo_contrato varchar(30) not null check ((tipo_contrato in ('EMPRESTIMO','FINANCIAMENTO','SEGURO','CONSIGNADO','CARTAO','CAMBIO','OUTROS'))), valor numeric(19,4), valor_parcela numeric(19,4), primary key (id));
create table aurix.contratos_assinaturas (id bigint generated by default as identity, data_atualizacao timestamp(6), data_criacao timestamp(6) not null, tenant_id varchar(64), versao integer not null, assinada boolean not null, assinante_documento varchar(14) not null, assinante_nome varchar(200), assinante_tipo varchar(20) not null check ((assinante_tipo in ('CLIENTE','GARANTE','AVALISTA','CORRETOR','INSTITUICAO'))), contrato_id bigint not null, data_assinatura timestamp(6), hash_documento varchar(128), ip varchar(45), user_agent varchar(500), valida boolean not null, primary key (id));
create table aurix.contratos_versoes (id bigint generated by default as identity, data_atualizacao timestamp(6), data_criacao timestamp(6) not null, tenant_id varchar(64), versao integer not null, contrato_id bigint not null, dados_json JSONB, data_versao timestamp(6) not null, motivo_alteracao varchar(300), numero_versao integer not null, primary key (id));
create table aurix.templates_contrato (id bigint generated by default as identity, data_atualizacao timestamp(6), data_criacao timestamp(6) not null, tenant_id varchar(64), versao integer not null, codigo varchar(50) not null unique, corpo_texto TEXT not null, nome varchar(200) not null, status varchar(20) not null check ((status in ('ATIVO','INATIVO'))), tipo_contrato varchar(30) not null check ((tipo_contrato in ('EMPRESTIMO','FINANCIAMENTO','SEGURO','CONSIGNADO','CARTAO','CAMBIO','OUTROS'))), primary key (id));

-- Índices
CREATE INDEX idx_versoes_produto_produto_id ON aurix.versoes_produto (produto_id);
CREATE INDEX idx_regras_elegibilidade_produto_id ON aurix.regras_elegibilidade (produto_id);
CREATE INDEX idx_tarifas_produto_produto_id ON aurix.tarifas_produto (produto_id);
CREATE INDEX idx_produtos_tipo_status ON aurix.produtos (tipo_produto, status);
CREATE INDEX idx_contratos_cliente_id ON aurix.contratos (cliente_id);
CREATE INDEX idx_contratos_status ON aurix.contratos (status);
CREATE INDEX idx_contratos_versoes_contrato_id ON aurix.contratos_versoes (contrato_id);
CREATE INDEX idx_contratos_assinaturas_contrato_id ON aurix.contratos_assinaturas (contrato_id);
CREATE INDEX idx_contratos_assinaturas_documento ON aurix.contratos_assinaturas (assinante_documento);

-- Chaves estrangeiras
ALTER TABLE aurix.versoes_produto ADD CONSTRAINT FK_versoes_produto_produto FOREIGN KEY (produto_id) REFERENCES aurix.produtos;
ALTER TABLE aurix.regras_elegibilidade ADD CONSTRAINT FK_regras_elegibilidade_produto FOREIGN KEY (produto_id) REFERENCES aurix.produtos;
ALTER TABLE aurix.tarifas_produto ADD CONSTRAINT FK_tarifas_produto_produto FOREIGN KEY (produto_id) REFERENCES aurix.produtos;
ALTER TABLE aurix.contratos_versoes ADD CONSTRAINT FK_contratos_versoes_contrato FOREIGN KEY (contrato_id) REFERENCES aurix.contratos;
ALTER TABLE aurix.contratos_assinaturas ADD CONSTRAINT FK_contratos_assinaturas_contrato FOREIGN KEY (contrato_id) REFERENCES aurix.contratos;
