spring:
  application:
    name: svc-finance-mgmt
  profiles:
    active: dev

server:
  port: 8089

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
  server:
    port: 9089

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
