server:
  port: 8082
  servlet:
    context-path: /

management:
  server:
    port: 9082
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aurix_credit
    username: aurix
    password: aurix
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

aurix:
  credit:
    scoring:
      model-path: classpath:models/scoring/
  shared:
    kafka:
      bootstrap-servers: localhost:9092
      enabled: true
    redis:
      enabled: false
      port: 6379
