-- ============================================================
-- Aurix Compliance - COAF, PLD/AML, PEP, LGPD (V1)
-- ============================================================

-- ------------------------------------------------------------
-- COAF - Conselho de Controle de Atividades Financeiras
-- ------------------------------------------------------------
CREATE TABLE aurix.coaf_notificacoes (
    id bigint generated by default as identity,
    data_atualizacao timestamp(6),
    data_criacao timestamp(6) not null,
    tenant_id varchar(64),
    versao integer not null,
    codigo_notificacao varchar(255) not null unique,
    cliente_id bigint,
    cpf_cnpj varchar(14) not null,
    nome_cliente varchar(255) not null,
    tipo_notificacao varchar(50) not null,
    status varchar(50) not null,
    data_ocorrencia timestamp(6) not null,
    data_notificacao timestamp(6),
    prazo_notificacao timestamp(6) not null,
    motivo_suspeita varchar(255),
    descricao_operacao TEXT,
    valor_operacao numeric(18,2),
    moeda varchar(10) default 'BRL',
    tipo_operacao varchar(100),
    canal_operacao varchar(20),
    instituicao_origem varchar(200),
    instituicao_destino varchar(200),
    dados_transacao TEXT,
    xml_notificacao TEXT,
    observacoes TEXT,
    dentro_prazo boolean default true,
    dias_restantes integer,
    primary key (id)
);

CREATE INDEX idx_coaf_notificacoes_cliente ON aurix.coaf_notificacoes(cliente_id);
CREATE INDEX idx_coaf_notificacoes_status ON aurix.coaf_notificacoes(status);
CREATE INDEX idx_coaf_notificacoes_prazo ON aurix.coaf_notificacoes(prazo_notificacao);

CREATE TABLE aurix.coaf_relatorios (
    id bigint generated by default as identity,
    data_atualizacao timestamp(6),
    data_criacao timestamp(6) not null,
    tenant_id varchar(64),
    versao integer not null,
    codigo_relatorio varchar(255) not null unique,
    tipo_relatorio varchar(50) not null,
    status varchar(50) not null,
    data_inicio_periodo timestamp(6) not null,
    data_fim_periodo timestamp(6) not null,
    data_geracao timestamp(6) not null,
    data_envio timestamp(6),
    total_notificacoes integer not null,
    total_transacoes_analisadas integer not null,
    resumo_estatistico JSONB,
    conteudo_relatorio TEXT,
    xml_relatorio TEXT,
    hash_relatorio varchar(100),
    observacoes TEXT,
    primary key (id)
);

-- ------------------------------------------------------------
-- PLD/AML - Prevencao a Lavagem de Dinheiro
-- ------------------------------------------------------------
CREATE TABLE aurix.aml_regras (
    id bigint generated by default as identity,
    data_atualizacao timestamp(6),
    data_criacao timestamp(6) not null,
    tenant_id varchar(64),
    versao integer not null,
    codigo_regra varchar(255) not null unique,
    nome_regra varchar(255) not null,
    descricao_regra TEXT,
    tipo_regra varchar(50) not null,
    status varchar(50) not null,
    peso_score integer not null default 10,
    limite_ativacao integer not null,
    parametros_regra TEXT,
    executar_automaticamente boolean default true,
    notificar_alerta boolean default true,
    data_vigencia_inicio timestamp(6),
    data_vigencia_fim timestamp(6),
    primary key (id)
);

CREATE TABLE aurix.aml_alertas (
    id bigint generated by default as identity,
    data_atualizacao timestamp(6),
    data_criacao timestamp(6) not null,
    tenant_id varchar(64),
    versao integer not null,
    codigo_alerta varchar(255) not null unique,
    cliente_id bigint not null,
    cpf_cnpj varchar(14) not null,
    nome_cliente varchar(255),
    regra_id bigint,
    nome_regra varchar(255) not null,
    tipo_alerta varchar(50) not null,
    status varchar(50) not null,
    score_risco integer not null default 0,
    data_deteccao timestamp(6) not null,
    data_investigacao timestamp(6),
    data_resolucao timestamp(6),
    valor_transacao numeric(18,2),
    descricao_alerta TEXT,
    detalhes_deteccao TEXT,
    investigador_responsavel varchar(100),
    parecer_investigacao TEXT,
    motivo_resolucao varchar(100),
    evidencias JSONB,
    observacoes TEXT,
    primary key (id)
);

CREATE INDEX idx_aml_alertas_cliente ON aurix.aml_alertas(cliente_id);
CREATE INDEX idx_aml_alertas_status ON aurix.aml_alertas(status);
CREATE INDEX idx_aml_alertas_score ON aurix.aml_alertas(score_risco DESC);

CREATE TABLE aurix.aml_investigacoes (
    id bigint generated by default as identity,
    data_atualizacao timestamp(6),
    data_criacao timestamp(6) not null,
    tenant_id varchar(64),
    versao integer not null,
    codigo_investigacao varchar(255) not null unique,
    alerta_id bigint not null,
    codigo_alerta varchar(255) not null,
    cliente_id bigint not null,
    status varchar(50) not null,
    data_inicio timestamp(6) not null,
    data_prazo timestamp(6),
    data_conclusao timestamp(6),
    investigador_responsavel varchar(100) not null,
    supervisor_revisor varchar(100),
    descricao_investigacao TEXT,
    evidencias_coletadas TEXT,
    parecer_investigador TEXT,
    parecer_supervisor TEXT,
    decisao_final varchar(50),
    justificativa_decisao TEXT,
    reportado_coaf boolean default false,
    data_reporte_coaf timestamp(6),
    timeline_eventos JSONB,
    observacoes TEXT,
    primary key (id)
);

CREATE INDEX idx_aml_investigacoes_alerta ON aurix.aml_investigacoes(alerta_id);
CREATE INDEX idx_aml_investigacoes_status ON aurix.aml_investigacoes(status);

-- ------------------------------------------------------------
-- PEP - Pessoas Politicamente Expostas
-- ------------------------------------------------------------
CREATE TABLE aurix.pep_clientes (
    id bigint generated by default as identity,
    data_atualizacao timestamp(6),
    data_criacao timestamp(6) not null,
    tenant_id varchar(64),
    versao integer not null,
    cliente_id bigint not null,
    cpf_cnpj varchar(14) not null,
    nome_completo varchar(255) not null,
    classificacao varchar(50) not null,
    status varchar(50) not null,
    cargo_funcao varchar(255),
    orgao_instituicao varchar(255),
    esfera_governo varchar(50),
    uf_exercicio varchar(2),
    data_inicio_cargos timestamp(6),
    data_fim_cargos timestamp(6),
    renda_declarada numeric(18,2),
    patrimonio_declarado numeric(18,2),
    cep_cliente varchar(8),
    profissao varchar(100),
    nivel_risco varchar(50) not null default 'MEDIO',
    data_verificacao timestamp(6),
    data_proxima_verificacao timestamp(6),
    observacoes TEXT,
    historico_cargos JSONB,
    vinculos_familiares JSONB,
    primary key (id)
);

CREATE INDEX idx_pep_clientes_cliente ON aurix.pep_clientes(cliente_id);
CREATE INDEX idx_pep_clientes_status ON aurix.pep_clientes(status);
CREATE INDEX idx_pep_clientes_risco ON aurix.pep_clientes(nivel_risco);

-- ------------------------------------------------------------
-- LGPD - Consentimento e Bases Legais
-- ------------------------------------------------------------
CREATE TABLE aurix.lgpd_bases_legais (
    id bigint generated by default as identity,
    data_atualizacao timestamp(6),
    data_criacao timestamp(6) not null,
    tenant_id varchar(64),
    versao integer not null,
    codigo_base_legal varchar(255) not null unique,
    nome_base_legal varchar(255) not null,
    tipo_base_legal varchar(50) not null,
    status varchar(50) not null,
    descricao_base_legal TEXT,
    referencia_legal varchar(500),
    cliente_id bigint,
    data_inicio_vigencia timestamp(6) not null,
    data_fim_vigencia timestamp(6),
    observacoes TEXT,
    primary key (id)
);

CREATE INDEX idx_lgpd_bases_legais_cliente ON aurix.lgpd_bases_legais(cliente_id);
CREATE INDEX idx_lgpd_bases_legais_status ON aurix.lgpd_bases_legais(status);

CREATE TABLE aurix.lgpd_log_acessos (
    id bigint generated by default as identity,
    data_atualizacao timestamp(6),
    data_criacao timestamp(6) not null,
    tenant_id varchar(64),
    versao integer not null,
    cliente_id bigint not null,
    tipo_acesso varchar(50) not null,
    descricao_operacao varchar(255) not null,
    responsavel_operacao varchar(100) not null,
    ip_origem varchar(100),
    data_operacao timestamp(6) not null,
    resultado varchar(50) not null,
    detalhes_operacao TEXT,
    observacoes TEXT,
    primary key (id)
);

CREATE INDEX idx_lgpd_log_acessos_cliente ON aurix.lgpd_log_acessos(cliente_id);
CREATE INDEX idx_lgpd_log_acessos_data ON aurix.lgpd_log_acessos(data_operacao);
CREATE INDEX idx_lgpd_log_acessos_tipo ON aurix.lgpd_log_acessos(tipo_acesso);
