server:
  port: 8205
  servlet:
    context-path: /

management:
  server:
    port: 9205
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

spring:
  flyway:
    enabled: true
    validate-on-migrate: true
    validate-migration-naming: true
    locations: classpath:db/migration
    schemas: aurix
  datasource:
    url: jdbc:postgresql://localhost:5432/aurix_compliance
    username: aurix
    password: aurix
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

aurix:
  shared:
    kafka:
      bootstrap-servers: localhost:9092
      enabled: true
    redis:
      enabled: false
      port: 6379
